### ISSUE TITLE
json are not parse properly into params when content-type application/json

### ISSUE THREAD

**Issue by faustoct** [padrino/padrino-framework#2139] opened 2017-06-05 00:12 UTC
#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behavior?
when upgarded to 0.14.2 version $.post('/something',{val: 1},function(){}) stopped working

*If the current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem via https://github.com/ or https://gist.github.com/*

#### What is the expected behavior?
should get json through params variable

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?
padrino 0.14.2

**Comment by faustoct** [comment] 2017-06-05 00:17
a workaround is documented here

http://padrinorb.com/guides/controllers/parsing-params/

add it to your app.rb

```
use Rack::Parser, :content_types => {
  'application/json'  => Proc.new { |body| ::MultiJson.decode body }
}
```

some point it had been done by default without add any extra line of code. Would be nice have it again.

**Comment by ujifgc** [comment] 2017-06-05 06:11
Closing as not a bug. Padrino never parsed JSON as params.

At some point it might have been some Rack components default behavior.

**Closed by ujifgc** 2017-06-05 06:11 UTC

**Comment by faustoct** [comment] 2017-06-05 11:47
great, thanks.
