### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by federicolucca** [padrino/padrino-framework#1968] opened 2015-09-27 15:01 UTC
Hi,

i am not able to understand why, i have a small project, it worked fine for 3-4months in a remote server. After the update of  ubuntu,something goes wrong. After the login in the admin console,i have the 403 forbidden page. i started a project from empty folder like a test, only following the padrino website tutorial,and after all, i have the same issue, both in local and in remote .
i didn't modified the files apps.rb,app.rb,config.ru only the initial config from padrino generator.

what it could be?
Federico

**Comment by namusyaka** [comment] 2015-09-27 15:17
@federicolucca Could you provide a minimal project with Gemfile.lock?
I'd like to reproduce and fix your problem.

**Comment by federicolucca** [comment] 2015-10-01 08:38
After a bit of debugging,i found out the problem could be related to the domain . i assume that the cache or something save the old rack session cookie. I will try to give you an example

Federico

**Comment by ujifgc** [comment] 2015-10-08 07:18
Closing as looks like not a Padrino issue.

**Closed by ujifgc** 2015-10-08 07:18 UTC
