### ISSUE TITLE
Memory usage in 0.13.0

### ISSUE THREAD

**Issue by cookiebody** [padrino/padrino-framework#1975] opened 2015-10-15 17:27 UTC
My project has 70 controllers, contains 1297 routes. The source file size is 4 MB.
When use 0.13, the startup process is slow, about 1 minute. 
After startup, the memory is larger than 880 MB. 

Use 0.12.5, starup process is just 10 seconds, and the memory is just 122 MB after startup.

Environment:
Ruby v2.2
Puma v2.14
CentOS 6.5

**Comment by ujifgc** [comment] 2015-10-16 10:58
Interesting! Can you give any examples of your routes? Are they regexps or strings?

**Comment by cookiebody** [comment] 2015-10-16 14:04
It's simple, no regexps:
```ruby
get :index
post :edit, :with => :id
put :update, :with => :id

**Comment by ujifgc** [comment] 2015-10-17 05:37
Confirmed.

0.12 +6.6 MB usage:

```
Running Padrino::HugeRouterBenchmark
total kB          253048   54420   47188
bench_calling_sample     0.004770        0.016475        0.062645        0.276180        1.155195
total kB          259628   60860   53628
```

0.13 +72.2 MB usage:
```
Running Padrino::HugeRouterBenchmark
total kB          274640   75692   68484
bench_calling_sample     0.004567        0.016682        0.074811        0.362379        2.265402
total kB          346848  140052  132844
```

The offending code is here:

```
    180588  /home/ujif/pro/padrino-framework/padrino-core/lib/padrino-core/path_router/compiler.rb:77
```

**Comment by nesquena** [comment] 2015-10-17 05:39
@namusyaka thoughts on this. Thanks for profiling @ujifgc. Looks like we need to do a 0.13.1 soon?

**Comment by namusyaka** [comment] 2015-10-17 06:42
Now, our router compiles all routes into the complicated regexps before startup. Our router may be faster than 0.12.5, but it's given by using many memory.

I received @cookiebody's institution of problem, and then I'd like to implement two handlers as followings.

## The recognizer handler (see https://github.com/namusyaka/pendragon/blob/master/lib/pendragon/engine/recognizer.rb)
Use liner-search. So this maybe slow but it doesn't use many memory for not having regexps.

## The compiler handler
Re-implement compiler handler which is for getting only one route (so compiler won't use many memory ).

Thoughts?

**Comment by ujifgc** [comment] 2015-10-17 06:45
Memory usage can also be halved if we use `Mustermann.new(path, :uri_decode => false)`

**Comment by ujifgc** [comment] 2015-10-17 08:12
>5k+ routes

Padrino 0.13 + Mustermann uri_decode => true (default)

```
Running Padrino::HugeRouterBenchmark
total kB          231760   34972   28056
bench_calling_sample     0.004624        0.016634        0.070547        0.346639        2.149676
total kB          333456  126644  119576
```

Padrino 0.13 + Mustermann uri_decode => false
```
Running Padrino::HugeRouterBenchmark
total kB          231828   35180   28040
bench_calling_sample     0.005137        0.017078        0.072626        0.353611        2.152586
total kB          301508   96076   88848
```

Padrino 0.12.5 + http_router
```
Running Padrino::HugeRouterBenchmark
total kB          236736   40024   32960
bench_calling_sample     0.004736        0.016137        0.062812        0.265002        1.091113
total kB          258880   58072   50920
```

**Comment by ujifgc** [comment] 2015-10-17 08:26
> 512 routes

0.12.5

```
Running Padrino::HugeRouterBenchmark
total kB          236676   40052   32864
bench_calling_sample     0.005831        0.016215        0.063527        0.279086        1.124821
total kB          268584   67852   60576
```

0.13

```
Running Padrino::HugeRouterBenchmark
total kB          231808   34944   28004
bench_calling_sample     0.004809        0.016922        0.078706        0.441583        3.452375
total kB          560528  335152  328124
```

>1024 routes

0.12.5
```
Running Padrino::HugeRouterBenchmark
total kB          236716   39864   32920
bench_calling_sample     0.005045        0.016473        0.064086        0.274779        1.128071
total kB          293560   92692   85596
```

0.13 Init time is painful
```
Running Padrino::HugeRouterBenchmark
total kB          231852   35020   28052
bench_calling_sample     0.004925        0.017443        0.078519        0.676301        5.599227
total kB         1459652 1160108 1153052
```

0.13 with uri_decode => false init time is half of painful
```
Running Padrino::HugeRouterBenchmark
total kB          231748   35068   28076
bench_calling_sample     0.005091        0.017611        0.078188        0.541323        5.329440
total kB          992048  712648  705504
```

@namusyaka, what's your prognosis on recognizer memory usage and init time?

**Comment by pchaganti** [comment] 2015-10-17 12:03
Seeing the same thing with the memory bloat. Any chance there will be a 0.13.1 soon with a fix for this?

thanks!

**Comment by namusyaka** [comment] 2015-10-17 12:59
@ujifgc Great point. i'll see the option when i get home.
If we can get the performance by specifying the option, there is no reason why it's not disabled.

also, i think 0.13.1 should be released as soon as possible.

Sorry for the late response and inconvenience.

**Comment by ujifgc** [comment] 2015-10-17 16:02
Unfortunately just that `uri_decode` option is not nearly enough to level with 0.12.5 memory usage.

**Comment by namusyaka** [comment] 2015-10-17 16:03
Can you provide your memory profiling code? I'm going to dig into this problem.

**Comment by ujifgc** [comment] 2015-10-17 16:10
Sure, https://github.com/padrino/padrino-framework/tree/mem-profile

Run with `bundle exec rake mem`. This code runs in Linux, not sure about another systems:

```
`pmap -x #{$$} | tail -1``
```

**Closed** 2015-10-18 08:49 UTC

**Comment by namusyaka** [comment] 2015-10-18 08:57
@cookiebody Thanks for reporting the issue. Maybe the issue has been fixed on the edge. 
Please let me know if you still have the issue !

**Comment by nesquena** [comment] 2015-10-18 08:59
@cookiebody yes please let us know how your app fares on edge. Looks like we should push 0.13.1 soon. 

Thanks @ujifgc and @namusyaka

**Comment by cookiebody** [comment] 2015-10-18 10:58
@namusyaka @ujifgc @nesquena 
Thanks for quick reply and upgrade, I have tested with 0.13.1. 
The memory usage is similar with 0.12.5 now.
