### ISSUE TITLE
Padrino does not show exceptions: "undefined method `bytesize' for #<Array:0x00000005320668>"

### ISSUE THREAD

**Issue by catswithbenefits** [padrino/padrino-framework#1893] opened 2015-03-11 07:49 UTC
Padrino on several of my Mac workstations and Linux servers does not show any exception traces in the web browser, making debugging user error reports very difficult.

**Steps to reproduce:**
- Download and extract newest Padrino Version
- Generate a new project
- Generate a new controller inside that project
- Create an action that does a *throw "error"*

**Observed behaviour**
- Webbrowser output is: 
> Internal Server Error
> undefined method `bytesize' for #<Array:0x00000005320668>
> WEBrick/1.3.1 (Ruby/2.1.4/2014-10-27) at XXX:3000

- The stacktrace is outputted to stdout only

**Expected behaviour**
- I'd like to see the stacktrace and error message in the browser.

Thanks for a fix or an explanation on how to fix this problem.

**Comment by catswithbenefits** [comment] 2015-03-11 07:53
Update: This is the exception stack trace that is outputted in stdout:

RuntimeError - Exception test in main Controller:
	/var/www/ueber2.0/staging/public/app/controllers/main.rb:9:in `block (2 levels) in <top (required)>'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:735:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:735:in `block in route'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:62:in `[]'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:62:in `block (3 levels) in process_destination_path'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:62:in `block (2 levels) in process_destination_path'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:62:in `catch'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:62:in `block in process_destination_path'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:37:in `instance_eval'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:37:in `process_destination_path'
	(eval):159:in `block in call'
	(eval):148:in `catch'
	(eval):148:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/http_router-0.11.1/lib/http_router.rb:288:in `raw_call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/http_router-0.11.1/lib/http_router.rb:142:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:1169:in `route!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:1154:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/application/routing.rb:1152:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/reloader/rack.rb:22:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/logger.rb:420:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/router.rb:84:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/router.rb:75:in `each'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/router.rb:75:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
[2015-03-11 08:15:04] ERROR NoMethodError: undefined method `bytesize' for #<Array:0x00000005320668>
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/utils.rb:335:in `bytesize'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/router.rb:84:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/router.rb:75:in `each'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.2/lib/padrino-core/router.rb:75:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

**Comment by namusyaka** [comment] 2015-03-11 07:59
Could you try to use padrino 0.12.5?


2015年3月11日水曜日、catswithbenefits<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

**Comment by ujifgc** [comment] 2015-03-11 08:19
@catswithbenefits please publish a failing project with Gemfile.lock. After looking at your stack trace it seems impossible to follow your "Steps to reproduce" instructions and get the stack trace you provided since the version of Padrino in it is not the newest.

**Comment by ujifgc** [comment] 2015-03-11 08:22
Another thought: you might be running Padrino 0.12.2 because you have it installed in your system and you start it with `padrino s`. Try starting it with `bundle exec padrino s` if your Gemfile is up to date.

**Comment by catswithbenefits** [comment] 2015-03-11 08:52
I can confirm that a fresh project with Padrino 0.12.5 does work on Mac. Updating my bigger live project to 0.12.5 however does not resolve the issue, neither does starting the server with bundle exec. My spider senses tell me it must have something to do with old/incompatible versions of Webrick or Sinatra, but this is just a guess.

I suppose this is just a user issue, I'd appreciate it if somebody more knowledgable than me would have a look at my attached Gemfile/Gemfile.lock

**Gemfile**
```
source 'https://rubygems.org'

gem 'mail', '2.5.3'
gem 'pg'
gem 'rake'
gem 'savon'
gem 'bcrypt'
gem 'erubis', '~> 2.7.0'
gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'composite_primary_keys'
gem 'safe_attributes'
gem 'mysql2'
gem "binding_of_caller"
gem 'padrino', '>= 0.12.5'
gem "sinatra-activerecord"
gem 'paper_trail', '~> 3.0.6'
gem 'phone'
gem 'htmlentities'
gem 'hipchat'
gem "psych"
```

**Gemfile.lock**
```
GEM
  remote: https://rubygems.org/
  specs:
    activemodel (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
    activerecord (4.2.0)
      activemodel (= 4.2.0)
      activesupport (= 4.2.0)
      arel (~> 6.0)
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    akami (1.2.2)
      gyoku (>= 0.4.0)
      nokogiri
    arel (6.0.0)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    composite_primary_keys (8.0.0)
      activerecord (~> 4.2.0)
    debug_inspector (0.0.2)
    erubis (2.7.0)
    gyoku (1.2.3)
      builder (>= 2.1.2)
    hipchat (1.4.0)
      httparty
    htmlentities (4.3.3)
    http_router (0.11.1)
      rack (>= 1.0.0)
      url_mount (~> 0.2.1)
    httparty (0.13.3)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    httpi (2.3.0)
      rack
    i18n (0.7.0)
    json (1.8.2)
    macaddr (1.7.1)
      systemu (~> 2.6.2)
    mail (2.5.3)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.25.1)
    mini_portile (0.6.2)
    minitest (5.5.1)
    moneta (0.7.20)
    multi_xml (0.5.5)
    mysql2 (0.3.18)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nori (2.4.0)
    padrino (0.12.5)
      padrino-admin (= 0.12.5)
      padrino-cache (= 0.12.5)
      padrino-core (= 0.12.5)
      padrino-gen (= 0.12.5)
      padrino-helpers (= 0.12.5)
      padrino-mailer (= 0.12.5)
      padrino-support (= 0.12.5)
    padrino-admin (0.12.5)
      padrino-core (= 0.12.5)
      padrino-helpers (= 0.12.5)
    padrino-cache (0.12.5)
      moneta (~> 0.7.0)
      padrino-core (= 0.12.5)
      padrino-helpers (= 0.12.5)
    padrino-core (0.12.5)
      activesupport (>= 3.1)
      http_router (~> 0.11.0)
      padrino-support (= 0.12.5)
      rack (< 1.6.0)
      rack-protection (>= 1.5.0)
      sinatra (~> 1.4.2)
      thor (~> 0.18)
    padrino-gen (0.12.5)
      bundler (~> 1.0)
      padrino-core (= 0.12.5)
    padrino-helpers (0.12.5)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.12.5)
      tilt (~> 1.4.1)
    padrino-mailer (0.12.5)
      mail (~> 2.5.3)
      padrino-core (= 0.12.5)
    padrino-support (0.12.5)
      activesupport (>= 3.1)
    paper_trail (3.0.7)
      activerecord (>= 3.0, < 5.0)
      activesupport (>= 3.0, < 5.0)
    pg (0.18.1)
    phone (1.2.3)
    polyglot (0.3.5)
    psych (2.0.13)
    rack (1.5.2)
    rack-protection (1.5.3)
      rack
    rake (10.4.2)
    safe_attributes (1.0.10)
      activerecord (>= 3.0.0)
    savon (2.10.1)
      akami (~> 1.2)
      builder (>= 2.1.2)
      gyoku (~> 1.2)
      httpi (~> 2.3)
      nokogiri (>= 1.4.0)
      nori (~> 2.4)
      uuid (~> 2.3.7)
      wasabi (~> 3.4)
    sinatra (1.4.5)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    sinatra-activerecord (2.0.5)
      activerecord (>= 3.2)
      sinatra (~> 1.0)
    systemu (2.6.4)
    thor (0.19.1)
    thread_safe (0.3.4)
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    url_mount (0.2.1)
      rack
    uuid (2.3.7)
      macaddr (~> 1.0)
    wasabi (3.4.0)
      httpi (~> 2.0)
      nokogiri (>= 1.4.2)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord (>= 3.1)
  bcrypt
  binding_of_caller
  composite_primary_keys
  erubis (~> 2.7.0)
  hipchat
  htmlentities
  mail (= 2.5.3)
  mysql2
  padrino (>= 0.12.5)
  paper_trail (~> 3.0.6)
  pg
  phone
  psych
  rake
  safe_attributes
  savon
  sinatra-activerecord

```

**Comment by ujifgc** [comment] 2015-03-11 09:36
Your [stack trace](https://github.com/padrino/padrino-framework/issues/1893#issuecomment-78218846) looks invalid. You have Padrino 0.12.5 in your Gemfile.lock and Padrino 0.12.2 in your stack trace.

To fix an issue a knowledgeable person would be required to first reproduce it, but it is seems impossible in this case without practicing black and/or blood magic.

**Comment by catswithbenefits** [comment] 2015-03-11 09:45
Sorry for the confusion - the stacktrace was generated using 0.12.2, the Gemfiles are from 0.12.5.
Please find the up to date stacktrace below: The error message is the same:

```
RuntimeError - Exception test in main Controller:
	/var/www/ueber2.0/staging/public/app/controllers/main.rb:9:in `block (2 levels) in <top (required)>'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/application/routing.rb:504:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/application/routing.rb:504:in `block in route'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/ext/http_router.rb:33:in `[]'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/ext/http_router.rb:33:in `block (3 levels) in process_destination_path'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/ext/http_router.rb:33:in `block (2 levels) in process_destination_path'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/ext/http_router.rb:33:in `catch'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/ext/http_router.rb:33:in `block in process_destination_path'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/ext/http_router.rb:8:in `instance_eval'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/ext/http_router.rb:8:in `process_destination_path'
	(eval):159:in `block in call'
	(eval):148:in `catch'
	(eval):148:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/http_router-0.11.1/lib/http_router.rb:288:in `raw_call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/application/routing.rb:931:in `route!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/application/routing.rb:915:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/application/routing.rb:913:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/reloader/rack.rb:22:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/logger.rb:420:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:84:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:75:in `each'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:75:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
[2015-03-11 10:00:20] ERROR NoMethodError: undefined method `bytesize' for #<Array:0x00000002c2f018>
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/utils.rb:335:in `bytesize'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:84:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:75:in `each'
	/usr/local/rvm/gems/ruby-2.1.4/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:75:in `call'
	/usr/local/rvm/gems/ruby-2.1.4/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

```

**Comment by nesquena** [comment] 2015-03-11 09:48
Starting from the top, what code do you have in Controller: /var/www/ueber2.0/staging/public/app/controllers/main.rb:9? Do you see anything suspicious on line 9?

**Comment by catswithbenefits** [comment] 2015-03-11 09:50
Yes, I have a raise exception there:

```
  get :exception, :map => '/exception' do
          raise "Exception test in main Controller"
  end
```

That's what I use to analyse the issue.

**Comment by nesquena** [comment] 2015-03-11 10:01
Looking at the stack trace beneath the bytesize error https://github.com/sinatra/sinatra/blob/master/lib/sinatra/show_exceptions.rb it's definitely a bit odd. I was thinking maybe a sinatra or rack version mismatch is likely at fault. Unfortunately I'm not able to reproduce this with the Padrino apps I have running 0.12.5 or a new project. Any other hints on what we'd have to do to reproduce?

**Comment by ujifgc** [comment] 2015-03-11 10:58
The provided `Gemfile.lock` work fine with `ruby 2.1.0` and a dummy project. I'm gonna test it against `ruby 2.1.4` some time later. It looks extremely strange that the variable here: `/usr/local/rvm/gems/ruby-2.1.4/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37` is kind of Array.

**Comment by catswithbenefits** [comment] 2015-03-11 11:02
I did some more trying out and also removed the mention of *rack* in the Gemfile.
Now I have my exceptions in the browser again, yay!

However, there is a new problem now: my `views/layouts/application.rhtml` application-template (ERB) is not applied anymore when rendering views.
Rendering views using `render "index", :layout => "application.rhtml"`works however.

Before I change all my render-statements: Is there a sane way to set the default template? I didn't read anything on the padrino blog about breaking changes.

**Comment by ujifgc** [comment] 2015-03-17 18:26
Closing as invalid. You claim to have removed `rack` from a Gemfile though you posted here a Gemfile without `rack` in it.

You need to open a separate issue and follow [these instructions](https://github.com/padrino/padrino-framework#bug-reporting) if you have problems with render options.

**Closed by ujifgc** 2015-03-17 18:26 UTC
Labels: revalidate
