### ISSUE TITLE
Padrino setting response.body as a String instead of [String] for exceptions

### ISSUE THREAD

**Issue by postmodern** [padrino/padrino-framework#1867] opened 2015-01-15 23:44 UTC
I noticed that with padrino >= 0.12.2, when an exception occurs the `response.body` is a `String`, instead of an `[String, ...]`. This causes an exception in `Sinatra::ShowException`:

<pre>
[2015-01-15 15:41:34] ERROR NoMethodError: undefined method `join' for #<String:0x007f091fc15690>
	/home/hal/.gem/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
	/home/hal/.gem/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/hal/.gem/ruby/2.0.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
	/home/hal/.gem/ruby/2.0.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
	/home/hal/.gem/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/home/hal/.gem/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/home/hal/.gem/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/home/hal/.gem/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/home/hal/.gem/ruby/2.0.0/gems/padrino-core-0.12.4/lib/padrino-core/router.rb:84:in `block in call'
	/home/hal/.gem/ruby/2.0.0/gems/padrino-core-0.12.4/lib/padrino-core/router.rb:75:in `each'
	/home/hal/.gem/ruby/2.0.0/gems/padrino-core-0.12.4/lib/padrino-core/router.rb:75:in `call'
	/home/hal/.gem/ruby/2.0.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/home/hal/.rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
</pre>

**Comment by namusyaka** [comment] 2015-01-16 06:05
This is caused by [this change](https://github.com/rack/rack/commit/893a2c505a3a43b4f224b50ea06567dacb473cae).
The problem has been fixed in edge of sinatra, but it isn't released yet.

**Closed** 2015-01-16 06:05 UTC

**Comment by postmodern** [comment] 2015-01-21 20:40
How can I backport this into existing Padrino apps?

**Comment by postmodern** [comment] 2015-01-21 20:56
Nevermind, I just copied the ShowException class into `lib/` and now I can see backtraces again :)

**Comment by ujifgc** [comment] 2015-01-21 23:02
In my projects I just locked rack on `1.5.2` version until new Sinatra is released.
