### ISSUE TITLE
Layout does not after updating Padrino to 0.12.5

### ISSUE THREAD

**Issue by catswithbenefits** [padrino/padrino-framework#1904] opened 2015-04-01 15:08 UTC
I updated a project from Padrino 0.12.2 to 0.12.5
After the update my (ERB) layouts don't work anymore. They used to work with the older version. I did not do any code changes.

The layout is stored in `app/views/layouts/application.rhtml`a (sample) view is stored in `app/views/main/index.rhtml`. There is no special code to activate the layout, as I did not need it before.

What can I do? 

**Gemfile**
```
source 'https://rubygems.org'

gem "skylight"
gem 'mail', '2.5.3'
gem 'thor', '0.18.0'
gem 'pg'
gem 'rake'
gem 'savon'
gem 'bcrypt'
gem 'erubis'
gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'composite_primary_keys'
gem 'safe_attributes'
gem 'mysql2'
gem "binding_of_caller"
gem 'padrino', "=0.12.5"
gem "sinatra-activerecord"
gem 'paper_trail', '~> 3.0.6'
gem 'phone'
gem 'htmlentities'
gem 'hipchat'
gem "psych"
gem "thin"
```

**System stats**
```
jojo-macmini:~ admin$ padrino -v
Padrino v. 0.12.5
jojo-macmini:~ admin$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
jojo-macmini:~ admin$ uname -a
Darwin jojo-macmini.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

**Comment by catswithbenefits** [comment] 2015-04-02 07:44
I can reproduce the error with a fresh project. 

```
$ padrino g project -e erb myapp
$ cd my app
$ bundle
$ padrino g controller ctrl
# create index action in fresh controller:
#   get :index do
#     render 'index'
#   end

# create view in app/views/ctrl/index.rhtml (Contents: index.rhtml)
# create layout in app/views/layouts/application.erb (Contents: application.erb <%= yield %>)
```

Observation: No layout applied. 

The problem also occurs when using the HAML renderer.

Rendering the view with render 'index', :layout => "application" does work however
Calling `layout :application` in the app.rb does not help.

Please help!

**Comment by ujifgc** [comment] 2015-04-02 08:55
Is there any particular reason to use '.rhtml' extension? It works fine if you use '.html.erb' instead.

**Comment by catswithbenefits** [comment] 2015-04-02 09:06
Using `.html.erb` for my index-file does work.
Renaming `application.rhtml` to `application.html.erb`(or .erb, .html, .rb for that matter) does not work - the application layout is still not applied.

**Comment by ujifgc** [comment] 2015-04-02 12:34
Padrino does not recognize '.rhtml' extension as ERB format. This extension is legacy and was dropped 80 years ago by Rails community. Is there any particular reason to use it? How do you end up using it, is there any Padrino or documentation that encourages it?

**Comment by catswithbenefits** [comment] 2015-04-02 12:39
I like '.rthml', that's why I use it. It used to work when I started the project with 0.11, so I kinda stuck with it.

However even using ".html.erb" for my view and layout file does not resolve the issue.

**Comment by ujifgc** [comment] 2015-04-02 14:50
Padrino '0.12.2' is the only Padrino version that applies default layout to unrecognized rendering engines ('.rhtml' is unrecognized). This behavior is not intended and was introduced as regression. This bug was reported in #1727 and fixed in Padrino '0.12.3'.

I can not reproduce the issue using proper '.html.erb' extension.

To make Padrino '0.12.5' allow default layout for '.rhtml' extension you can add to your app:

```
Padrino::Rendering.engine_configurations[:rhtml] = Padrino::Rendering.engine_configurations[:erb]
```

This fix however does not work on Padrino edge. I will investigate further.

**Comment by catswithbenefits** [comment] 2015-04-02 15:09
To clarify my problem: I am unable to get an ERB layout to work with 0.12.5 - no matter what extensions I use.

I documented the steps I took in my second posting. Can you get a layout to work or do you see a blatant error on my side?

**Comment by ujifgc** [comment] 2015-04-02 15:14
I followed your steps and I can not reproduce your problem using proper '.html.erb' extension. Please, publish your app demonstrating broken behavior with Gemfile.lock on Github.

**Comment by catswithbenefits** [comment] 2015-04-02 15:25
OK, now I think I'm having a break-through: For the layout to work it is imperative for both the view and layout file to have the extension `.html.erb`. Actually naming the view/layout ".erb" seems to suffice. Using rhtml means no cake (Even when setting the engine_configurations as you suggested)

I think this resolves the actual problem for me. However I think supporting deprecated extensions and not using layouts is confusing (at least for me)- please change the default behavior, if possible.

**Comment by ujifgc** [comment] 2015-05-04 11:52
Setting `layout 'application.rhtml'` adds this layout even if the engine is not supported for layouts by Padrino. No actual need for https://github.com/padrino/padrino-framework/issues/1904#issuecomment-88934300

As for deprecation, right now '.rhtml' is supported by Tilt, that's why it gets rendered.

Closing the issue as resolved.

**Closed by ujifgc** 2015-05-04 11:52 UTC
Labels: bug
